#!/bin/bash
#
# Copyright 2021 Telefónica Investigación y Desarrollo, S.A.U
#
# This file is part of the PerseoFE component
#
# PerseoFE is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# PerseoFE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with PerseoFE.
# If not, see http://www.gnu.org/licenses/.
#
# For those usages not covered by the GNU Affero General Public License
# please contact with: sc_support at telefonica dot com the GNU Affero General Public License please contact
# with iot_support at tid dot es

docker image push $IMAGE_NAME-pm2 

# FIXME: distroless stuff disabled. See https://github.com/telefonicaid/iotagent-json/issues/891
#docker image push $IMAGE_NAME-distroless


